sonar.projectKey=analizador-medico
sonar.projectName=Analizador Medico
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://localhost:9000

sonar.login= sqp_69375f190c6469935eda76497e669821e02c0d04

sonar.language=py